services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/certs:ro
      - ./frontend:/usr/frontend:ro
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
        - .env
    depends_on:
      - postgres
  video-streamer:
    container_name: v-streamer
    build:
      context: video-streamer
      dockerfile: Dockerfile
  
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
