services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/certs:ro
      - ./frontend:/usr/frontend:ro

        # backend:
    #image: your-backend-image
      #restart: always
      #expose:
      
      #  - "8000"
    # environment:
    #   - VAR=VALUE

